#!/bin/bash -ex

git mv $1 $2

oldname="$(basename $1)"
newname="$(basename $2)"

repodir=$(git rev-parse --show-toplevel)
pushd $repodir > /dev/null
    perl -i -pe "s/\b${oldname}\b/${newname}/g" $(git grep --full-name -l ${oldname})
popd

