#!/usr/bin/env bash

PID=$(pgrep -u $USER gnome-session)

eval `strings /proc/$PID/environ | while read line; do
   KEY="$(echo $line | sed -n 's/\([[:upper:]_]*\)=.*/\1/p')"
   VALUE="$(echo $line | sed -n 's/[[:upper:]_]*=\([^"]*\)/\1/p')"
   [ -z "$KEY" ] && continue;
   [ -z "$VALUE" ] && continue;
   echo "export $KEY='$VALUE'"
done`

zsh
