#!/bin/bash -e

if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo "No git no dice"
    exit 1
fi
repodir=$(git rev-parse --show-toplevel)
reponame="$(basename $repodir)"

pushd $repodir > /dev/null
if [ "$reponame" = "eos-knowledge-apps" ]; then
    jhbuild run eos-travel-en
elif [ "$reponame" = "eos-knowledge-lib" ]; then
    jhbuild run eos-travel-en
elif [ "$reponame" = "eos-encyclopedia" ]; then
    jhbuild run eos-encyclopedia com.endlessm.encyclopedia-en
elif [ "$reponame" = "eos-knowledge-engine" ]; then
    jhbuild-knowledge-engine
elif [ "$reponame" = "xapian-bridge" ]; then
    jhbuild-xapian-bridge
elif [ "$reponame" = "eos-pantheon-tools" ]; then
    ./node_modules/sails/bin/sails.js console
elif [ "$reponame" = "eos-resume" ]; then
    jhbuild run gjs $repodir/resume-app.js
elif [ "$reponame" = "eos-finance" ]; then
    jhbuild run gjs $repodir/finance-app.js
elif [ "$reponame" = "yelp-xsl" ]; then
    jhbuild run yelp
elif [ "$reponame" = "gnome-user-docs" ]; then
    jhbuild run yelp
elif [ "$reponame" = "gnome-getting-started-docs" ]; then
    jhbuild run yelp
else
    jhbuild run $reponame
fi
popd
