#!/bin/bash -ex
# Install old knowledge app bundles

# 2.2
install-bundle com.endlessm.howto-en https://d10gnxo2okxo8t.cloudfront.net/uploads/bundle/e03ac29392f5dbd35786cd7fa65260c410d0275513b568dad7d2d15c656b6cd4.bundle
install-bundle com.endlessm.maternity-en https://d10gnxo2okxo8t.cloudfront.net/uploads/bundle/7d4f881ab2c0daf44d7f0a455e378b02b6400c0f8c5fef3aadea8679fb52e895.bundle
install-bundle com.endlessm.encyclopedia-es https://d10gnxo2okxo8t.cloudfront.net/uploads/bundle/b4e470bced1ef2473b3259a5bc35ce52ba0f5dc1e26f16569dd288e01d349761.bundle
# 2.3
install-bundle com.endlessm.health-en https://d10gnxo2okxo8t.cloudfront.net/uploads/bundle/27fe402c83fb1cf339bbcdb300c047fc5858c5f36ebad7c01f568d3eef1a4d28.bundle
install-bundle com.endlessm.cooking-en https://d10gnxo2okxo8t.cloudfront.net/uploads/bundle/6d150965b8f775f3fda6ce52cb57f435337ee09455a32788dd2b9667887c251f.bundle
