#!/bin/bash -ex
# Symlinks all the actual locations these config files need to be in right back
# to this directory, so they can be easily version controlled.

SCRIPT_DIR=$(dirname $(readlink -f $0))
DOTFILE_DIR=${SCRIPT_DIR}/home

function backup_and_link() {
    SOURCE=${DOTFILE_DIR}/${1}
    DEST=${HOME}/.${1}
    mkdir -p $(dirname $DEST)
    # If its a symlink, just overwrite. Otherwise make a backup.
    if [ -e $DEST -a ! -h $DEST ]; then
        backup=${DEST}.old
        if [ -e $backup ]; then
            echo "$DEST and $backup exist, clean up your shit"
            exit 1
        fi
        echo "Moving existing $DEST to ${DEST}.old"
        mv $DEST $backup
    fi
    ln -sTf $SOURCE $DEST
}

pushd $DOTFILE_DIR
for file in $(find .  -maxdepth 1 -type f -printf '%P\n'); do
    backup_and_link $file
done
# List nested directories explicitly, cause we may want to choose how to link
# them. i.e. link entire diretory or individual files
backup_and_link local/share/fonts
popd
