#!/bin/bash -ex
# Symlinks all the actual locations these config files need to be in right back
# to this directory, so they can be easily version controlled.

SCRIPT_DIR=$(dirname $(readlink -f $0))
DOTFILE_DIR="${SCRIPT_DIR}/home"

function backup_and_link() {
    SOURCE="${DOTFILE_DIR}/${1}"
    DEST="${HOME}/.${1}"
    mkdir -p $(dirname "${DEST}")
    # If its a symlink, just overwrite. Otherwise make a backup.
    if [ -e "${DEST}" -a ! -h "${DEST}" ]; then
        BACKUP=${DEST}.old
        if [ -e "${BACKUP}" ]; then
            echo ""${DEST}" and ${BACKUP} exist, clean up your shit"
            exit 1
        fi
        echo "Moving existing ${DEST} to ${DEST}.old"
        mv "${DEST}" "${BACKUP}"
    fi
    ln -sTf "${SOURCE}" "${DEST}"
}

shopt -s globstar
pushd "${DOTFILE_DIR}"
for file in **; do
    if [ -d "${file}" ]; then
        continue
    fi
    backup_and_link "${file}"
done
popd
