#!/bin/bash -e
# Symlinks all the actual locations these config files need to be in right back
# to this directory, so they can be easily version controlled.

SCRIPT_DIR=$(dirname $(readlink -f $0))

function backup_and_link() {
    mkdir -p $(dirname $2)
    # If its a symlink, just overwrite. Otherwise make a backup.
    if [ -e $2 -a ! -h $2 ]; then
        backup=${2}.old
        if [ -e $backup ]; then
            echo "$2 and $backup exist, clean up your shit"
            exit 1
        fi
        echo "Moving existing $2 to ${2}.old"
        mv $2 $backup
    fi
    ln -sTf $1 $2
}

backup_and_link ${SCRIPT_DIR}/endless/eos.modules ~/eos.modules
backup_and_link ${SCRIPT_DIR}/endless/jhbuildrc ~/.jhbuildrc
backup_and_link ${SCRIPT_DIR}/git/git_template ~/.git_template
backup_and_link ${SCRIPT_DIR}/git/gitconfig ~/.gitconfig
backup_and_link ${SCRIPT_DIR}/git/gitignore ~/.gitignore
backup_and_link ${SCRIPT_DIR}/shell/jshintrc ~/.jshintrc
backup_and_link ${SCRIPT_DIR}/shell/matt.zsh-theme ~/.oh-my-zsh/custom/matt.zsh-theme
backup_and_link ${SCRIPT_DIR}/shell/tmux.conf ~/.tmux.conf
backup_and_link ${SCRIPT_DIR}/shell/profile ~/.profile
backup_and_link ${SCRIPT_DIR}/shell/quiltrc ~/.quiltrc
backup_and_link ${SCRIPT_DIR}/shell/zshrc ~/.zshrc
backup_and_link ${SCRIPT_DIR}/subl ~/.config/sublime-text-3/Packages/User
backup_and_link ${SCRIPT_DIR}/local/logout.desktop ~/.local/share/applications/logout.desktop
backup_and_link ${SCRIPT_DIR}/local/restart.desktop ~/.local/share/applications/restart.desktop
backup_and_link ${SCRIPT_DIR}/local/shutdown.desktop ~/.local/share/applications/shutdown.desktop
