#!/bin/bash -ex
# Simple setup script for debian systems.

SCRIPT_DIR=$(dirname $(readlink -f $0))

# apt install stuff
sudo apt-get update
sudo apt-get install -y zsh tmux vim git

# brew install stuff
curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
brew install fzf gh micro diff-so-fancy cowsay tree xclip lolcat fortune

# zsh
if [ ! -e $HOME/.oh-my-zsh ]; then
  git clone https://github.com/ohmyzsh/ohmyzsh.git ~/checkout/oh-my-zsh
  git clone https://github.com/romkatv/powerlevel10k.git ~/checkout/powerlevel10k
  ln -sTf ~/checkout/oh-my-zsh ~/.oh-my-zsh
  ln -sTf ~/checkout/powerlevel10k ~/.oh-my-zsh/custom/themes/powerlevel10k
fi

$SCRIPT_DIR/link

# gsettings
if [[ $XDG_CURRENT_DESKTOP == *GNOME* ]]; then
  gsettings set org.gnome.desktop.background picture-uri "file://${SCRIPT_DIR}/background.jpg"
  gsettings set org.gnome.desktop.peripherals.touchpad natural-scroll true
  gsettings set org.gnome.desktop.input-sources xkb-options "['ctrl:nocaps']"
fi

sudo chsh -s $(which zsh) $USER
zsh -c "source $HOME/.zshrc && say 'DONE! Reboot and you should be all set.'"
