#!/bin/bash -ex
# Really simple setup script for debian systems

SCRIPT_DIR=$(dirname $(readlink -f $0))

# fzf
if [ ! -e $HOME/.fzf ]; then
  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  ~/.fzf/install
fi

# Grab sudo rights
sudo true

$SCRIPT_DIR/link

# apt install stuff
sudo apt-get update
sudo apt-get install -y fortunes cowsay xclip dos2unix zsh tmux tree vim git ruby

# gem install shit we don't have in debians
sudo gem install gist lolcat

# gsettings
if [[ $XDG_CURRENT_DESKTOP == *GNOME* ]]; then
  gsettings set org.gnome.desktop.background picture-uri "file://${SCRIPT_DIR}/background.jpg"
  gsettings set org.gnome.desktop.peripherals.touchpad natural-scroll true
  gsettings set org.gnome.desktop.input-sources xkb-options "['ctrl:nocaps']"
  gsettings set org.gtk.Settings.Debug enable-inspector-keybinding true
fi

sudo chsh -s $(which zsh) $USER
zsh -c "source $HOME/.zshrc && say 'DONE! Reboot and should be all set in your
new shell.'"
