#!/bin/bash -ex
# Really simple setup script for debian systems

SCRIPT_DIR=$(dirname $(readlink -f $0))

# apt install stuff
sudo apt-get update
sudo apt-get install -y fortunes cowsay xclip dos2unix zsh tmux tree vim git ruby
# gem install shit we don't have in debians
sudo gem install gist lolcat

# fzf
if [ ! -e $HOME/.fzf ]; then
  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  ~/.fzf/install
fi

# zplug
if [ ! -e $HOME/.zplug ]; then
  git clone --depth 1 https://github.com/zplug/zplug.git ~/.zplug
fi

$SCRIPT_DIR/link

# gsettings
if [[ $XDG_CURRENT_DESKTOP == *GNOME* ]]; then
  gsettings set org.gnome.desktop.background picture-uri "file://${SCRIPT_DIR}/background.jpg"
  gsettings set org.gnome.desktop.peripherals.touchpad natural-scroll true
  gsettings set org.gnome.desktop.input-sources xkb-options "['ctrl:nocaps']"
fi

sudo chsh -s $(which zsh) $USER
zsh -c "source $HOME/.zshrc && zinstall && say 'DONE! Reboot and you should be all set.'"
