#!/bin/bash -e

if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo "No git no dice"
    exit 1
fi
repodir=$(git rev-parse --show-toplevel)
reponame="$(basename $repodir)"

pushd $repodir > /dev/null
if [ "$reponame" = "eos-knowledge-db-build" ]; then
    jhbuild run python setup.py develop --prefix=$HOME/install
elif [ "$reponame" = "eos-knowledge-engine" ]; then
    npm install && npm run sass
elif [ "$reponame" = "eos-pantheon-tools" ]; then
    npm install
else
    jhbuild make
fi
popd
