#!/bin/bash -ex

sudo systemctl stop xapian-bridge.service
sudo systemctl stop xapian-bridge.socket
sudo systemctl stop eos-knowledge-engine.service
sudo systemctl stop eos-knowledge-engine.socket

trap "sudo systemctl start xapian-bridge.socket; sudo systemctl start eos-knowledge-engine.socket" SIGHUP SIGINT SIGTERM
parallel -- 'jhbuild run xapian-bridge' 'sleep 1; jhbuild run node $HOME/checkout/eos-knowledge-engine/server.js'
