#!/usr/bin/python

import os
import sys

SAVE_FILE = os.path.expanduser('~/.fav-dirs')

COLORS = ['\033[91m', '\033[92m', '\033[93m', '\033[94m', '\033[95m', '\033[96m']
END = '\033[0m'

def rpad(item, spaces):
  item = str(item)
  pad = (spaces - len(item)) * ' '
  return item + pad

if sys.argv[1] == 'record':
  # load data from file
  # update a counter
  # save to temp file
  # mv to to main file
  print 'record'

if sys.argv[1] == 'pick':
  # load data from file
  print 'pick'

if sys.argv[1] == 'list':
  # load data from file
  for i in range(15):
    print COLORS[i % len(COLORS)], rpad(i + 1, 4), 'dirname', END
