#!/bin/bash -ex

APP_ID=$1
BUNDLE_URL=$2
SIGNATURE_URL=${BUNDLE_URL/bundle/signature}.asc

TMP_DIR=$(mktemp -dt ${APP_ID}.XXXXXXXXXX)

pushd $TMP_DIR
wget $BUNDLE_URL -O $APP_ID.bundle
wget $SIGNATURE_URL -O $APP_ID.asc
chmod +rwx .
eamctl uninstall $APP_ID || true
eamctl install $APP_ID
popd

rm -r $TMP_DIR
