#!/usr/bin/env bash

# 1. Search for text in files using Ripgrep
# 2. Interactively restart Ripgrep with reload action
# 3. Open the file in vscode


INITIAL_QUERY="${*:-}"
IFS=: read -ra selected < <(
  FZF_DEFAULT_COMMAND="symbol-search $(printf %q "$INITIAL_QUERY")"  \
  fzf --ansi \
      --disabled --query "$INITIAL_QUERY" \
      --bind "change:reload:sleep 0.1; symbol-search {q} || true" \
      --bind='ctrl-s:abort' \
      --delimiter : \
      --preview 'bat --color=always {1} --highlight-line {2}' \
      --height 100%
)
[ -n "${selected[0]}" ] && code --goto "${selected[0]}:${selected[1]}"
