#!/bin/bash -e

# Link flatpak ekn suscriptions to jhbuild

FLATPAK_DIR=/var/lib/flatpak
JHBUILD_PREFIX=$HOME/install

for APP_DIR in $FLATPAK_DIR/app/*; do
    APP_ID=$(basename $APP_DIR)
    SUBSCRIPTIONS_PATH="share/ekn/data/$APP_ID/com.endlessm.subscriptions"
    SUBSCRIPTION_SOURCE="$APP_DIR/current/active/files/$SUBSCRIPTIONS_PATH"
    SUBSCRIPTIONS_DEST="$JHBUILD_PREFIX/$SUBSCRIPTIONS_PATH"
    if [ -e $SUBSCRIPTIONS_DEST ]; then
        echo "Already content for $APP_ID; skipping"
        continue
    fi
    if [ -d $SUBSCRIPTION_SOURCE ]; then
        echo "Linking content for $APP_ID"
        mkdir -p $(basename $SUBSCRIPTIONS_DEST)
        ln -s $SUBSCRIPTION_SOURCE $SUBSCRIPTIONS_DEST
    fi
done