#!/bin/bash -ex

RUNTIME=$HOME/.local/share/flatpak/runtime/com.endlessm.Sdk/$(uname -m)/master/active/files

bwrap --bind $RUNTIME /usr \
      --bind $HOME $HOME \
      --ro-bind /etc /etc \
      --ro-bind /sys/block /sys/block \
      --ro-bind /sys/bus /sys/bus \
      --ro-bind /sys/class /sys/class \
      --ro-bind /sys/dev /sys/dev \
      --ro-bind /sys/devices /sys/devices \
      --proc /proc \
      --dev /dev \
      --symlink /run /var/run \
      --symlink usr/lib /lib \
      --symlink usr/lib64 /lib64 \
      --symlink usr/bin /bin \
      --symlink usr/sbin /sbin \
      --dir /tmp \
      --dir /var/lib/dpkg \
      --dir /var/tmp \
      --dir /var/data \
      --dir /var/cache \
      --chdir $HOME/checkout \
      /bin/bash
